### ISSUE TITLE
ERROR: Parent module 'asyncio' not loaded

### ISSUE THREAD

**Issue by takasoft** [RLBot/RLBotScratchInterface#3]
The program doesn't start because of this error. Do you have suggestions?

```
INFO:rlbot[    setup_manager.py:127 -                  run() ] Match has started
INFO:rlbot[    setup_manager.py:130 -                  run() ] Press 'r' to reload all agents, or 'q' to exit
INFO:scratch_mgr[  scratch_manager.py:35 -                start() ] Starting scratch manager
Process Process-6:
Traceback (most recent call last):
  File "C:\Python\Python35\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Python\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\takao\repos\rocket_league\venv\lib\site-packages\rlbot\botmanager\helper_process_manager.py", line 53, in run_helper_process
    helper.start()
  File "C:\Users\takao\repos\rocket_league\scratch_bot\scratch_manager.py", line
39, in start
    asyncio.get_event_loop().run_until_complete(websockets.serve(self.data_exchange, port=PORT))
  File "C:\Python\Python35\lib\asyncio\events.py", line 632, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Python\Python35\lib\asyncio\events.py", line 617, in get_event_loop_policy
    _init_event_loop_policy()
  File "C:\Python\Python35\lib\asyncio\events.py", line 610, in _init_event_loop_policy
    from . import DefaultEventLoopPolicy
SystemError: Parent module 'asyncio' not loaded, cannot perform relative import
```

**Comment by tarehart** [comment]
Sorry about the error! Looks like you're currently using Python 3.5, which doesn't come with asyncio. Our main guidance is to install Python 3.6 and use that instead: https://www.python.org/ftp/python/3.6.7/python-3.6.7-amd64.exe

BUT you could also try running `pip install asyncio` in a command prompt which might be easier. I don't know if it will work.
